### ISSUE TITLE
snap package rejection due to 2 fails

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-snap#6]
checksums do not match. Please ensure the snap is created with either 'snapcraft pack <DIR>' (using snapcraft >= 2.38) or 'mksquashfs <dir> <snap> -noappend -comp xz -all-root -no-xattrs -no-fragments'. If using electron-builder, please upgrade to latest stable (>= 20.14.7). See https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/17 for details. security-snap-v2_squashfs_repack_checksum What does this mean?

found errors in file output: unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7', unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7/dist-packages', unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7/site-packages', unusual mode 'rwxr-sr-x' for entry './local/lib/python3.6', unusual mode 'rwxr-sr-x' for entry './local/lib/python3.6/dist-packages', unusual mode 'rwxr-sr-x' for entry './local/share/fonts' security-snap-v2_squashfs_files

**Comment by CAMOBAP** [comment]
Fixed

**Comment by ronaldtse** [comment]
Version 8 worked but version 9/10 still failed:

found errors in file output: unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7', unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7/dist-packages', unusual mode 'rwxr-sr-x' for entry './local/lib/python2.7/site-packages', unusual mode 'rwxrwsr-x' for entry './local/lib/python3.6', unusual mode 'rwxrwsr-x' for entry './local/lib/python3.6/dist-packages', unusual mode 'rwxr-sr-x' for entry './local/share/fonts' security-snap-v2_squashfs_files

checksums do not match. Please ensure the snap is created with either 'snapcraft pack <DIR>' (using snapcraft >= 2.38) or 'mksquashfs <dir> <snap> -noappend -comp xz -all-root -no-xattrs -no-fragments'. If using electron-builder, please upgrade to latest stable (>= 20.14.7). See https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/17 for details. security-snap-v2_squashfs_repack_checksum What does this mean?

How come?

**Comment by CAMOBAP** [comment]
@ronaldtse looks like Travis CI still works, could you please disable it?

**Comment by ronaldtse** [comment]
@CAMOBAP it was already disabled 21 hours ago, so it's not Travis running.

<img width="691" alt="Screen Shot 2020-05-14 at 3 02 43 PM" src="https://user-images.githubusercontent.com/11865/81903194-f9dfb280-95f3-11ea-89ab-01a2da8364cb.png">

**Comment by CAMOBAP** [comment]
@ronaldtse  hmm, very strange, could you please show/check the list of integrations in settings for this repo.

some third-party system builds snap using metanorma@ribose.com's credentials

**Comment by ronaldtse** [comment]
On this page you can see SnapCraft actually building the snaps:
https://snapcraft.io/metanorma/builds

<img width="1149" alt="Screen Shot 2020-05-14 at 3 25 33 PM" src="https://user-images.githubusercontent.com/11865/81905340-2943ee80-95f7-11ea-8b67-f57bc48f2e07.png">

Maybe these are the ones?

**Comment by ronaldtse** [comment]
<img width="856" alt="Screen Shot 2020-05-14 at 3 27 23 PM" src="https://user-images.githubusercontent.com/11865/81905529-69a36c80-95f7-11ea-9115-b8fda4b86a8c.png">

Yes they are from Snapcraft itself.

**Comment by ronaldtse** [comment]
I've disconnected the repo from Snapcraft so the builds won't happen again. Closing this.
